In [ ]:
1.Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
vect=np.zeros(10)
vect[4]=1
print(vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np
vect=np.arange(10,49)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np
vect=np.arange(0,9)
vect=vect.reshape(3,3)
vect

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np 
vect=[1,2,0,0,4,0]
print(np.nonzero(vect))

(array([0, 1, 4], dtype=int64),)


In [ ]:
5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
import numpy as np 
vect=np.random.randint(0,100,(10,10))
print(np.max(vect))
print(np.min(vect))

99
0


In [ ]:
6. Create a random vector of size 30 and find the mean value.

In [6]:
import numpy as np 
vect=np.random.randint(0,10000,(30))
print(np.mean(vect))

4691.533333333334
